Simplify applications
foundersandcoders/our-site-v3 pull request #204
Opened 2021-11-03 16:34 UTC by oliverjam

- [x] Slightly clean up homepage
   - [ ] Remove testimonials?
- [x] Totally revamp and simplify apply page
   - Only critical info and requirements remain
   - Ignores everything but Skills Bootcamp leading in to Apprenticeships
- [ ] Update application form to match DfE's validation
  - [ ] Remove Codewars username question

2021-11-03 17:08 UTC, yvonne-liu commented on src/index.md
> +  cta: Apply here
Should this say "application requirements" or something. I find that it's confusing one goes to the /apply and the other goes to the /form even though they look the same

2021-11-03 17:30 UTC, oliverjam commented on src/index.md
> +  cta: Apply here
Maybe "Start your application" ?

2021-11-03 17:40 UTC, oliverjam commented on src/forms/apply/index.md
> +        label: in training or education
I changed the radios component to support showing a different label to the submitted value (so we can fix the DfE's typos 🙃 without breaking their validation)

2021-11-03 17:41 UTC, yvonne-liu commented
Will need to fix the copy here too (remove references to Discord) @Albadylic 

https://www.foundersandcoders.com/requirements/weekly-prompts

2021-11-03 17:42 UTC, oliverjam commented on src/forms/apply/index.md
> +        label: Caring / leisure service
I'm assuming this is what they meant...

2021-11-03 17:43 UTC, Albadylic commented on src/forms/apply/index.md
> +        label: Caring / leisure service
I think it's three separate categories, as in

> caring, leisure and other service occupations

2021-11-03 17:45 UTC, Albadylic commented
> Will need to fix the copy here too (remove references to Discord) @Albadylic
> 
> https://www.foundersandcoders.com/requirements/weekly-prompts

I can push something to this PR to update the copy and add links to the files on the coursebook. I'll make a separate PR on the coursebook to add the content there.

2021-11-03 17:46 UTC, yvonne-liu commented
> * [x]  Slightly clean up homepage
>   
>   * [ ]  Remove testimonials?
> * [x]  Totally revamp and simplify apply page
>   
>   * Only critical info and requirements remain
>   * Ignores everything but Skills Bootcamp leading in to Apprenticeships
> * [x]  Update application form
>   
>   * [x]  change dates
>   * [x]  match DfE's validation
>   * [x]  remove Codewars username question too

We need to add the course dates back somewhere.

2021-11-03 17:56 UTC, oliverjam commented on src/forms/apply/index.md
> +        label: Caring / leisure service
Oh 🤦, will fix

2021-11-03 17:57 UTC, oliverjam commented
@Albadylic maybe it doesn't even make sense for them to be "weekly" prompts anymore, since from the Coursebook's perspective you can do them as fast or slow as you like

2021-11-03 18:02 UTC, Albadylic reviewed
🎉

2021-11-03 19:35 UTC, sofer commented on src/forms/apply/index.md
> +Second, a 12-week full-time programme, starting on TODO is this correct? April 4th 2022. This will require your full commitment from 9:45-18:00 Monday to Friday for 12 weeks.
Let's go with [May 9th](https://www.notion.so/foundersandcoders/Revised-schedule-for-2022-709d9b54bdde468ca69884f5d6fd6f94). We can always push it by a week if we need to.

2021-11-03 20:07 UTC, sofer commented on src/forms/apply/index.md
> +Second, a 12-week full-time programme, starting on TODO is this correct? April 4th 2022. This will require your full commitment from 9:45-18:00 Monday to Friday for 12 weeks.
Perhaps change the copy to something like, *"Second, if you secure an apprenticeship, a full-time commitment to your employer for the length of the apprenticeship, typically lasting for 15 months, starting on May 9th 2022."* 

It has become clear that it is critical to convey an early understanding of the length of the expected commitment.

2021-11-03 20:49 UTC, sofer requested changes

2021-11-03 20:49 UTC, sofer commented on src/forms/apply/index.md
> -    label: What is your Codewars username?
Codewars username still needed?

2021-11-03 20:49 UTC, sofer commented on src/forms/apply/index.md
>      label: What is your freeCodeCamp username?
fCC username still needed?

2021-11-03 20:49 UTC, sofer commented on src/forms/apply/index.md
>    - id: website
Remove Codewars kata (and freeCodeCamp?) from checklist. Also, date should probably be Sunday 12th December (or thereabouts). Assuming we are not interviewing.

2021-11-03 20:49 UTC, sofer commented on src/forms/apply/index.md
> -      - Any other ethnic groups (enter below)
At some point the DfE might ask for us to follow the [ONS list of ethnic groups](https://www.ethnicity-facts-figures.service.gov.uk/style-guide/ethnic-groups). Unlike for educational levels and occupational groups, they haven't specified it in their data submission spreadsheet, so changing this may not be a priority.

2021-11-03 20:49 UTC, sofer commented on src/forms/apply/index.md
>    - id: website
And references to Codewars and fCC may need removing from requirements/website

2021-11-04 10:09 UTC, oliverjam commented on src/apply.md
> +  text: Applications close at 21:00 GMT on December 10th
Based on previous data I'm not sure anyone has submitted more than ~5mins over the time. I don't mind jumping on to click the merge button anyway

2021-11-04 10:10 UTC, oliverjam commented on src/apply.md
> +   Complete all of the [prompts](/requirements/weekly-prompts) listed.
I think putting the specifics into the prompts page is fine

2021-11-04 10:11 UTC, oliverjam commented on src/forms/apply/index.md
> -    label: What is your Codewars username?
Not anymore, we dropped that requirement

2021-11-04 10:18 UTC, oliverjam commented on src/forms/apply/index.md
>      label: What is your freeCodeCamp username?
Yeah that's still a requirement

2021-11-04 10:22 UTC, oliverjam commented on src/forms/apply/index.md
> -      - Any other ethnic groups (enter below)
Yeah I pretty much copied that list for the first version. Unfortunately that meant Yvonne had to manually go through and change all the answers to match what the spreadsheet expected (there's validation on the columns that wasn't obvious to me at first—you only see it when you try to actually enter data that doesn't match)

2021-11-04 10:23 UTC, oliverjam commented on src/forms/apply/index.md
> +Second, a 12-week full-time programme, starting on TODO is this correct? April 4th 2022. This will require your full commitment from 9:45-18:00 Monday to Friday for 12 weeks.
Yeah I guess that's the important part now. Not everybody on the Skills Bootcamp is going to move on to the full-time course

2021-11-04 12:25 UTC, yvonne-liu commented on src/forms/apply/index.md
>    - id: website
No, Friday the 10th.

2021-11-04 17:36 UTC, yvonne-liu requested changes

2021-11-04 17:36 UTC, yvonne-liu commented on src/forms/apply/index.md
> +      - "yes - full-time employment"
Sorry but can these be capitalised (it's the only ones that aren't)

2021-11-04 17:44 UTC, yvonne-liu reviewed
> Have you been involved in our community?

Remove, or change to "Have you applied before: Y/N" 

> You have until 18:00 BST on Aug 27th to submit this application as well as finish all of your application requirements. Before that date, please make sure you double check your application.

Needs to change to 21:00 GMT on December 10th 

> I understand that I can keep working on the requirements until 18:00 BST Aug 27

Needs to change to 21:00 GMT on December 10th

2021-11-04 17:45 UTC, yvonne-liu commented
> We always try to make the selection process transparent. We will communicate to all applicants on Discord: how many applications we’ve received, how many applicants we are planning on interviewing, and how the interview will be structured

Remove

> We will consider many factors, including: your eligibility for our course; engagement with our Discord community; attendance at our meet-ups and workshops; representation of the change we’d like to see in the tech industry; and whether you finished the requirements by the deadline.

Remove

2021-11-04 17:47 UTC, oliverjam commented on src/forms/apply/index.md
> +      - "yes - full-time employment"
Yeah this came straight from the DfE. I'll do separate label/value again

2021-11-04 18:01 UTC, oliverjam commented
@yvonne-liu all those changes are made

2021-11-04 18:14 UTC, merged