Codewars requirements update
foundersandcoders/our-site-v3 pull request #80
Opened 2020-10-14 12:58 UTC by oliverjam

Change Codewars application requirement to a set list of kata. @sofer and I were thinking 4 kata per rank (so 16 total). We may want more than this though. We were also unsure whether to make every kata mandatory, or just ask them to complete a subset.

- Change /apply page to link to /requirements/codewars
   - Change requirements on /apply to numbered list so they're clearer
- Add /requirements/codewars page with list of kata applicants must complete
   - Includes introduction to Codewars and a form for checking which kata you've completed so far
   - The checkbox list also persists checked state offline so applicants can use it to keep track

![localhost_8080_requirements_codewars_](https://user-images.githubusercontent.com/9408641/95991461-b4cedf00-0e24-11eb-9a69-8868193d18d2.png)

Relates #79

2020-10-14 13:05 UTC, sofer commented
> We were also unsure whether to make every kata mandatory

I was quite keen on every kata being mandatory in the interests of clarity.

2020-10-14 13:07 UTC, sofer commented on src/pages/marketing/apply.md
> +   - Use an image carousel package like Flickity ⁠— we want to see your own code
Are we keeping the image carousel in for now?

2020-10-14 13:09 UTC, oliverjam commented on src/pages/marketing/apply.md
> +   - Use an image carousel package like Flickity ⁠— we want to see your own code
I haven't changed the website requirements yet, wanted to keep this PR focused on CW

2020-10-14 13:10 UTC, sofer commented
❤️ the "Check your progress" feature.

2020-10-14 13:12 UTC, sofer requested changes
Obviously, not ready to approve until we have a full set of kata

2020-10-14 13:14 UTC, oliverjam commented on src/pages/marketing/apply.md
> +   Complete at least 10 of [these Codewars challenges](/requirements/codewars).
Forgot to update this to "complete all of these"

2020-10-14 13:15 UTC, sofer commented on src/pages/marketing/apply.md
> +   - Contain a link to your _public_ freeCodeCamp profile
Perhaps we could gently signal that we are no longer checking freeCodeCamp by not requiring the link to the freeCodeCamp profile.

2020-10-14 22:23 UTC, oliverjam commented on src/pages/marketing/apply.md
> +   - Contain a link to your _public_ freeCodeCamp profile
I thought we decided not to change the fCC requirement for FAC21?

2020-10-19 11:06 UTC, oliverjam commented on src/pages/marketing/apply.md
> +   - Use an image carousel package like Flickity ⁠— we want to see your own code
I'll be pushing another PR for this later today

2020-10-19 13:00 UTC, jackherizsmith approved these changes

2020-10-19 13:00 UTC, jackherizsmith commented on src/pages/marketing/requirements/codewars.md
> +**You must complete all of these challenges before applying to Founders and Coders**. Codewars challenges are called "kata", and they have a "rank" to represent how difficult they are. 8 is the simpl
I wonder if it's worth including anything like "don't worry if more challenging ones seem impossible right now, you will get there with practice and patience"? Probably not that, but e.g. I might have checked a 5kyu just to get a sense of what to expect then felt like stressed if it felt unachievable?

2020-10-19 13:06 UTC, yvonne-liu commented on src/pages/marketing/requirements/codewars.md
> +**You must complete all of these challenges before applying to Founders and Coders**. Codewars challenges are called "kata", and they have a "rank" to represent how difficult they are. 8 is the simpl
I share similar concern, and I wonder since we actively share some beginner kata series (the ones we mentioned during curriculum circle) would it worth bringing them up here? I think what's not clear is that while we want you to do these 25 to considered, there are people who might benefit from doing *more* katas

2020-10-19 13:16 UTC, sofer approved these changes

2020-10-19 13:25 UTC, oliverjam commented on src/pages/marketing/requirements/codewars.md
> +**You must complete all of these challenges before applying to Founders and Coders**. Codewars challenges are called "kata", and they have a "rank" to represent how difficult they are. 8 is the simpl
Yeah I can definitely add something highlighting that these are the end-goal, not the journey. Most people will need to do further learning and practice elsewhere/on CW.

I still think that linking to other non-required kata here will confuse people, so would rather have that be a separate resource/something for meetups/coaching sessions etc.

2020-10-19 13:30 UTC, oliverjam commented on src/pages/marketing/requirements/codewars.md
> +**You must complete all of these challenges before applying to Founders and Coders**. Codewars challenges are called "kata", and they have a "rank" to represent how difficult they are. 8 is the simpl
But can I make that change after we merge this? Need to get the bulk of the changes in asap to avoid conflicts and stuff between the two PRs

2020-10-19 13:33 UTC, Albadylic approved these changes

2020-10-19 13:39 UTC, yvonne-liu approved these changes

2020-10-19 13:39 UTC, merged